[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = []

[start]
cmd = "pnpm --filter @workspace/discord-bot run dev"
